// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktgzaciforpkhnfdtbqm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0Z3phY2lmb3Jwa2huZmR0YnFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxMzk2NjYsImV4cCI6MjA2MDcxNTY2Nn0.o0uZDsoRWNTLHL2qOxWSNI-rHDSMW7ixPc1aJwYo28k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});